### ISSUE TITLE
1.20.4崩溃/1.20.4 Crash

### ISSUE THREAD

**Issue by HanYuCR** [TheGameratorT/McTitleFixer#14]
我在Modrinth看到最新的Titlefixer的版本是支持1.20.1~1.20.4的
I see in Modrinth that the latest version of Titlefixer supports 1.20.1~1.20.4
![image](https://github.com/TheGameratorT/McTitleFixer/assets/126944908/93bec20e-31e4-4bd9-b6b9-ceed3de92c98)
然后我下载了这个Mod，启动游戏时却崩溃了
Then I downloaded the mod and it crashed when I launched the game
![image](https://github.com/TheGameratorT/McTitleFixer/assets/126944908/b5e7817f-3fc1-47e2-a37e-6729fa1bce83)
***这是我最后一次启动后的log和crash-report文件
Here's the log and crash-report file after my last boot up
[latest.log](https://github.com/TheGameratorT/McTitleFixer/files/14066441/latest.log)
[crash-2024-01-26_23.13.22-client.txt](https://github.com/TheGameratorT/McTitleFixer/files/14066449/crash-2024-01-26_23.13.22-client.txt)

希望您可以快点解决，这一定会是一个很不错的Mod！
I hope you can get it sorted out quickly, it's going to be a great Mod for sure!
ps:我的英语不是很好，所以我用了DeepL，可能会有一些意思表达不当，望您谅解
ps:My English is not very good, so I use DeepL, there may be some improper expression of the meaning, I hope you understand.

**Comment by HanYuCR** [comment]
oh, ignore the strikethrough, pls. why did they get there??

**Comment by TheGameratorT** [comment]
Thanks for reaching out, I will fix as soon as I am available, probably tonight.
Maybe one day I will learn Chinese, looks really cool. I can already tell the title is something like "1.20.4 crumble something" :p
And your English is fine!

**Comment by HanYuCR** [comment]
Thx for the reply, and I’m glad you might learn Chinese in the future, I’m sure you can do it !  :D

**Comment by TheGameratorT** [comment]
Sorry for the delay, I have been busy.
Fixed on commit e29b538bfbc3d63179e5c380a6bbdf37e38f76c4 and already up on Modrinth.

**Comment by HanYuCR** [comment]
Thx a lot, I’ll try it later ! ;)
