### ISSUE TITLE
Incompatible with Ugly Scoreboard Fix

### ISSUE THREAD

**Issue by Scarlaid** [TheGameratorT/McTitleFixer#3]
Basically, the scoreboard settings in TitleFixer does conflict with [mentioned mod in title](https://gitlab.com/Lortseam/ugly-scoreboard-fix)
Will there be a compatible fix or I can only use either one out of two of them?

**Comment by TheGameratorT** [comment]
I'll see what I can do, I think it might be a conflict in the renderScoreboard redirections, since both my mod and his mod redirect the same function.

**Comment by Scarlaid** [comment]
I'm gonna close this because [Ugly Scoreboard Fix](https://gitlab.com/Lortseam/ugly-scoreboard-fix) seems to be broken with both this and in-game config, found an alternative as [CustomScoreboard](https://github.com/r0yzer/customscoreboard) with no conflict at all

thanks anyways man
