### ISSUE TITLE
Update to 1.19.2 please:)

### ISSUE THREAD

**Issue by ghost** [TheGameratorT/McTitleFixer#4]

**Comment by TheGameratorT** [comment]
Please refrain from posting passive-aggressive orders as issue titles, it's not like I am forced to do it just for you. Also, you have こんにちは incorrectly written on your GitHub profile.

**Comment by TheGameratorT** [comment]
I just tested it and the mod is working correctly in 1.19.2, Fabric modloader supports loading some mods from previous Minecraft versions.
Did you perhaps try using the 1.18 jar?

**Comment by TheGameratorT** [comment]
Closing this issue due to lack of response.

**Comment by ghost** [comment]
Hello @TheGameratorT, I oversaw this completely, sorry.
I wasn't testing it before, if it loads into 1.19. I saw just the 1.18 tag - my bad!
The mod loads fine into the game - could you update please the tags for 1.19.x on Modrinth/Curse?
Greetings.

**Comment by TheGameratorT** [comment]
Sure, greetings.
Also, unrelated note, こんにちわ is written as こんにちは, it's word is an exception.

**Comment by ghost** [comment]
Interesting, a native japanese helped me with this. I look into that again.
